# Generated by Django 5.2.9 on 2025-12-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroMEOWS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('unidad', models.CharField(max_length=20)),
                ('orden', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Parámetro MEOWS',
                'verbose_name_plural': 'Parámetros MEOWS',
                'ordering': ['orden'],
            },
        ),
    ]
