# Generated by Django 5.2.9 on 2025-12-30 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meows', '0002_formulario_paciente_parametro_medicion_medicionvalor'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='version',
            field=models.CharField(default='1.0', help_text='Versión del formulario (ej: 1.0, 2.0)', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='formulario',
            unique_together={('codigo', 'version')},
        ),
        migrations.CreateModel(
            name='RangoParametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_min', models.DecimalField(decimal_places=2, help_text='Valor mínimo del rango (inclusive)', max_digits=10)),
                ('valor_max', models.DecimalField(decimal_places=2, help_text='Valor máximo del rango (inclusive)', max_digits=10)),
                ('score', models.PositiveSmallIntegerField(help_text='Puntaje asignado a este rango (0-3)')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de evaluación (menor a mayor)')),
                ('activo', models.BooleanField(default=True)),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rangos', to='meows.parametro')),
            ],
            options={
                'verbose_name': 'Rango de Parámetro',
                'verbose_name_plural': 'Rangos de Parámetros',
                'ordering': ['parametro', 'orden', 'valor_min'],
                'indexes': [models.Index(fields=['parametro', 'activo', 'orden'], name='meows_rango_paramet_193d98_idx')],
            },
        ),
    ]
