# Generated by Django 5.2.9 on 2025-12-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meows', '0003_formulario_version_alter_formulario_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='codigo',
            field=models.CharField(max_length=30),
        ),
    ]
