# Generated by Django 5.2.9 on 2026-01-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meows', '0004_alter_formulario_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='aseguradora',
            field=models.CharField(blank=True, help_text='Nombre de la aseguradora', max_length=200),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cama',
            field=models.CharField(blank=True, help_text='Número o código de cama', max_length=50),
        ),
        migrations.AddField(
            model_name='paciente',
            name='edad',
            field=models.PositiveIntegerField(blank=True, help_text='Edad en años', null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_ingreso',
            field=models.DateField(blank=True, help_text='Fecha de ingreso al hospital', null=True),
        ),
    ]
