# Generated by Django 5.2.9 on 2026-01-05 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meows', '0005_paciente_aseguradora_paciente_cama_paciente_edad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='responsable',
            field=models.CharField(blank=True, help_text='Nombre del responsable del paciente', max_length=200),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='meows_riesgo',
            field=models.CharField(blank=True, choices=[('BLANCO', 'Blanco'), ('VERDE', 'Verde'), ('AMARILLO', 'Amarillo'), ('ROJO', 'Rojo')], max_length=10, null=True),
        ),
    ]
