# Generated by Django 5.2.10 on 2026-01-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meows', '0006_paciente_responsable_alter_medicion_meows_riesgo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genpacien',
            fields=[
                ('OID', models.IntegerField(db_column='OID', primary_key=True, serialize=False)),
                ('PACNUMDOC', models.CharField(db_column='PACNUMDOC', max_length=20)),
                ('PACTIPDOC', models.IntegerField(db_column='PACTIPDOC')),
                ('PACPRINOM', models.CharField(db_column='PACPRINOM', max_length=100)),
                ('PACSEGNOM', models.CharField(db_column='PACSEGNOM', max_length=100, null=True)),
                ('PACPRIAPE', models.CharField(db_column='PACPRIAPE', max_length=100)),
                ('PACSEGAPE', models.CharField(db_column='PACSEGAPE', max_length=100, null=True)),
                ('GPAFECNAC', models.DateTimeField(db_column='GPAFECNAC')),
                ('GPASEXPAC', models.IntegerField(db_column='GPASEXPAC')),
            ],
            options={
                'verbose_name': 'Paciente Externo (Genpacien)',
                'db_table': 'Genpacien',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='tipo_documento',
        ),
    ]
