# Generated by Django 5.2.11 on 2026-02-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meows', '0007_genpacien_remove_paciente_edad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adningreso',
            fields=[
                ('OID', models.IntegerField(db_column='OID', primary_key=True, serialize=False)),
                ('AINCONSEC', models.IntegerField(db_column='AINCONSEC')),
                ('AINFECING', models.DateTimeField(blank=True, db_column='AINFECING', null=True)),
                ('AINESTADO', models.IntegerField(blank=True, db_column='AINESTADO', null=True)),
            ],
            options={
                'verbose_name': 'Ingreso (Adningreso)',
                'db_table': 'ADNINGRESO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gendetcon',
            fields=[
                ('OID', models.IntegerField(db_column='OID', primary_key=True, serialize=False)),
                ('GDECODIGO', models.CharField(db_column='GDECODIGO', max_length=50)),
                ('GDENOMBRE', models.CharField(db_column='GDENOMBRE', max_length=200)),
            ],
            options={
                'db_table': 'GENDETCON',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gendiagno',
            fields=[
                ('OID', models.IntegerField(db_column='OID', primary_key=True, serialize=False)),
                ('DIACODIGO', models.CharField(db_column='DIACODIGO', max_length=20)),
                ('DIANOMBRE', models.CharField(db_column='DIANOMBRE', max_length=500)),
            ],
            options={
                'verbose_name': 'Diagnóstico (Gendiagno)',
                'db_table': 'GENDIAGNO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hcmwingin',
            fields=[
                ('OID', models.IntegerField(db_column='OID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'HCMWINGIN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hcndiapac',
            fields=[
                ('OID', models.IntegerField(db_column='OID', primary_key=True, serialize=False)),
                ('HCPDIAPRIN', models.IntegerField(blank=True, db_column='HCPDIAPRIN', null=True)),
            ],
            options={
                'db_table': 'HCNDIAPAC',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hcnfolio',
            fields=[
                ('OID', models.IntegerField(db_column='OID', primary_key=True, serialize=False)),
                ('HCNUMFOL', models.IntegerField(db_column='HCNUMFOL')),
                ('HCFECFOL', models.DateTimeField(blank=True, db_column='HCFECFOL', null=True)),
            ],
            options={
                'verbose_name': 'Folio Clínico',
                'db_table': 'HCNFOLIO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hpndefcam',
            fields=[
                ('OID', models.IntegerField(db_column='OID', primary_key=True, serialize=False)),
                ('HCACODIGO', models.CharField(db_column='HCACODIGO', max_length=50)),
                ('HCANOMBRE', models.CharField(db_column='HCANOMBRE', max_length=200)),
            ],
            options={
                'verbose_name': 'Cama (Hpndefcam)',
                'db_table': 'HPNDEFCAM',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hpnestanc',
            fields=[
                ('OID', models.IntegerField(db_column='OID', primary_key=True, serialize=False)),
                ('HESFECING', models.DateTimeField(blank=True, db_column='HESFECING', null=True)),
                ('HESFECSAL', models.DateTimeField(blank=True, db_column='HESFECSAL', null=True)),
            ],
            options={
                'db_table': 'HPNESTANC',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hpngrupos',
            fields=[
                ('OID', models.IntegerField(db_column='OID', primary_key=True, serialize=False)),
                ('HGRCODIGO', models.CharField(db_column='HGRCODIGO', max_length=50)),
                ('HGRNOMBRE', models.CharField(db_column='HGRNOMBRE', max_length=200)),
            ],
            options={
                'db_table': 'HPNGRUPOS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hpnsubgru',
            fields=[
                ('OID', models.IntegerField(db_column='OID', primary_key=True, serialize=False)),
                ('HSUCODIGO', models.CharField(db_column='HSUCODIGO', max_length=50)),
                ('HSUNOMBRE', models.CharField(db_column='HSUNOMBRE', max_length=200)),
            ],
            options={
                'db_table': 'HPNSUBGRU',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento', null=True),
        ),
    ]
