# Generated by Django 5.2.11 on 2026-03-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meows', '0008_adningreso_gendetcon_gendiagno_hcmwingin_hcndiapac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento del paciente', null=True),
        ),
    ]
