# Generated by Django 5.2.11 on 2026-03-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meows', '0009_alter_paciente_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmaPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_id', models.IntegerField()),
                ('formulario_id', models.IntegerField(blank=True, null=True)),
                ('template_huella', models.TextField()),
                ('imagen_huella', models.ImageField(blank=True, null=True, upload_to='huellas/')),
                ('usuario', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
