# Generated by Django 5.2.11 on 2026-03-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meows', '0010_firmapaciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmapaciente',
            name='imagen_firma',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/'),
        ),
    ]
