# Generated by Django 5.2.11 on 2026-03-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meows', '0011_firmapaciente_imagen_firma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmapaciente',
            name='formulario_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='firmapaciente',
            name='imagen_huella',
            field=models.ImageField(blank=True, null=True, upload_to='huellas_biometria/'),
        ),
        migrations.AlterField(
            model_name='firmapaciente',
            name='paciente_id',
            field=models.CharField(max_length=50),
        ),
    ]
