# Generated by Django 5.2.11 on 2026-03-17 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meows', '0012_alter_firmapaciente_formulario_id_and_more'),
        ('obstetricia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicion',
            name='atencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mediciones_meows', to='obstetricia.atencionparto'),
        ),
    ]
