# Generated by Django 5.2.11 on 2026-03-18 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meows', '0013_medicion_atencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='edad_gestacional',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Edad gestacional en semanas', null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='gestas',
            field=models.PositiveSmallIntegerField(blank=True, default=1, help_text='Número de gestas', null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nombre_acompanante',
            field=models.CharField(blank=True, help_text='Nombre del acompañante', max_length=200),
        ),
    ]
