# Generated by Django 5.2.11 on 2026-03-18 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meows', '0014_add_acompanante_edad_gestacional_gestas'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='tipo_sangre',
            field=models.CharField(blank=True, help_text='Tipo de sangre (O+, A-, etc.)', max_length=5),
        ),
    ]
