# Generated by Django 5.2.11 on 2026-08-11 13:38
# NOTA: 'diagnostico', 'n_controles_prenatales' y 'num_historia_clinica' ya existían
# como columnas en la base de datos (agregadas fuera del flujo de migraciones);
# esta migración solo alinea el historial de Django con el esquema real (--fake).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meows', '0015_add_tipo_sangre'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='diagnostico',
            field=models.TextField(blank=True, default='', help_text='Diagnóstico clínico inicial'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='n_controles_prenatales',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Número de controles prenatales', null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='num_historia_clinica',
            field=models.CharField(blank=True, default='', help_text='Número de historia clínica', max_length=50),
        ),
    ]
