# Generated by Django 5.2.11 on 2026-08-11 13:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meows', '0016_paciente_pending_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicion',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora real del monitoreo, registrada manualmente (entre 2 minutos y 4 horas antes del registro).'),
        ),
    ]
