# Generated by Django 5.2.11 on 2026-08-11 13:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meows', '0017_medicion_fecha_hora_editable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicion',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora real del monitoreo, registrada manualmente.'),
        ),
    ]
