# Generated by Django 5.2.11 on 2026-09-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meows', '0018_alter_medicion_fecha_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicion',
            name='dinamica_folio',
            field=models.IntegerField(blank=True, help_text="HCNFOLIO.OID de Dinámica del que se importó esta medición (solo si origen='dinamica').", null=True),
        ),
        migrations.AddField(
            model_name='medicion',
            name='origen',
            field=models.CharField(choices=[('manual', 'Manual'), ('dinamica', 'Dinámica')], default='manual', help_text='Si la medición se digitó a mano o se importó automáticamente desde Dinámica.', max_length=10),
        ),
    ]
