# Generated by Django 5.2.11 on 2026-09-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meows', '0019_medicion_dinamica_folio_medicion_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicion',
            name='alerta_pendiente',
            field=models.BooleanField(default=False, help_text='True mientras ninguna pantalla haya recogido/sonado la alerta de esta medición.'),
        ),
    ]
