# Generated by Django 5.2.11 on 2026-09-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meows', '0020_medicion_alerta_pendiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicion',
            name='alerta_generada_en',
            field=models.DateTimeField(blank=True, help_text='Momento en que se disparó la alerta — usado para la ventana de notificación del sidebar (ver api_alertas_pendientes en views.py). No es lo mismo que fecha_hora, que es cuándo se tomó el signo vital.', null=True),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='alerta_pendiente',
            field=models.BooleanField(default=False, help_text='True si esta medición generó una alerta MEOWS (riesgo alto/medio).'),
        ),
    ]
