# Generated by Django 5.2.11 on 2026-09-14 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meows', '0023_rangos_meows_frspa026'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FirmaPaciente',
        ),
    ]
