# Generated by Django 5.2.11 on 2026-09-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meows', '0024_delete_firmapaciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicion',
            name='responsable_dinamica',
            field=models.CharField(blank=True, help_text="Nombre de quien digitó esta toma en Dinámica (GENMEDICO.GMENOMCOM). Solo aplica a mediciones origen='dinamica'.", max_length=255, null=True),
        ),
    ]
