# Generated by Django 5.2.11 on 2026-09-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meows', '0025_medicion_responsable_dinamica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicion',
            name='origen',
            field=models.CharField(choices=[('manual', 'Manual'), ('dinamica', 'Dinámica'), ('triaje', 'Triaje')], default='manual', help_text='Si la medición se digitó a mano, se tomó en triaje (sin ingreso aún) o se importó automáticamente desde Dinámica.', max_length=10),
        ),
    ]
