# Generated by Django 5.2.11 on 2026-09-21 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meows', '0026_alter_medicion_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicionvalor',
            name='dinamica_oid',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
