# Generated by Django 5.2.11 on 2026-09-22 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meows', '0027_medicionvalor_dinamica_oid'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicion',
            name='ultima_correccion_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
