# Generated by Django 5.2.11 on 2026-09-22 19:55

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meows', '0028_medicion_ultima_correccion_en'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicion',
            options={'base_manager_name': 'todas', 'ordering': ['-fecha_hora'], 'verbose_name': 'Medición', 'verbose_name_plural': 'Mediciones'},
        ),
        migrations.AlterModelOptions(
            name='medicionvalor',
            options={'base_manager_name': 'todas', 'ordering': ['parametro__orden'], 'verbose_name': 'Valor de Medición', 'verbose_name_plural': 'Valores de Medición'},
        ),
        migrations.AlterModelManagers(
            name='medicion',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todas', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='medicionvalor',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todas', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='medicion',
            name='eliminado_en',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='medicionvalor',
            name='eliminado_en',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
