# Generated by Django 5.2.11 on 2026-09-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meows', '0029_alter_medicion_options_alter_medicionvalor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicion',
            name='registrado_por',
            field=models.CharField(blank=True, help_text='Profesional en sesión que registró esta toma en la app (Triaje).', max_length=255, null=True),
        ),
    ]
