# Generated by Django 5.2.9 on 2025-12-10 16:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aseguradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'aseguradora',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255, unique=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'item',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_historia_clinica', models.CharField(max_length=255, unique=True)),
                ('num_identificacion', models.CharField(max_length=255, unique=True)),
                ('nombres', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('tipo_sangre', models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, null=True)),
            ],
            options={
                'db_table': 'paciente',
                'ordering': ['nombres'],
            },
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('fecha_elabora', models.DateField()),
                ('fecha_actualizacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('num_hoja', models.PositiveIntegerField()),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('edad_snapshot', models.PositiveIntegerField(blank=True, null=True)),
                ('edad_gestion', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('g', 'G'), ('p', 'P'), ('c', 'C'), ('a', 'A'), ('v', 'V'), ('m', 'M')], max_length=1)),
                ('n_controles_prenatales', models.PositiveIntegerField(blank=True, null=True)),
                ('responsable', models.CharField(max_length=255)),
                ('aseguradora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formularios', to='clinico.aseguradora')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios', to='clinico.paciente')),
            ],
            options={
                'db_table': 'formulario',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('unidad', models.CharField(blank=True, max_length=50, null=True)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='clinico.item')),
            ],
            options={
                'db_table': 'parametro',
                'ordering': ['item_id', 'orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tomada_en', models.DateTimeField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='clinico.formulario')),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='clinico.parametro')),
            ],
            options={
                'db_table': 'medicion',
                'ordering': ['-tomada_en'],
            },
        ),
        migrations.CreateModel(
            name='FormularioItemParametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requerido', models.BooleanField(default=False)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros_formulario', to='clinico.formulario')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios_items', to='clinico.item')),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios_parametro', to='clinico.parametro')),
            ],
            options={
                'db_table': 'formulario_item_parametro',
            },
        ),
        migrations.CreateModel(
            name='CampoParametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_valor', models.CharField(choices=[('number', 'number'), ('text', 'text'), ('boolean', 'boolean'), ('json', 'json')], max_length=10)),
                ('unidad', models.CharField(blank=True, max_length=50, null=True)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='clinico.parametro')),
            ],
            options={
                'db_table': 'campo_parametro',
                'ordering': ['parametro_id', 'orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MedicionValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_number', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('valor_text', models.TextField(blank=True, null=True)),
                ('valor_boolean', models.BooleanField(blank=True, null=True)),
                ('valor_json', models.JSONField(blank=True, null=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='clinico.campoparametro')),
                ('medicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='clinico.medicion')),
            ],
            options={
                'db_table': 'medicion_valor',
                'indexes': [models.Index(fields=['medicion'], name='idx_valor_medicion'), models.Index(fields=['campo'], name='idx_valor_campo')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('valor_number__isnull', False), ('valor_text__isnull', True), ('valor_boolean__isnull', True), ('valor_json__isnull', True)), models.Q(('valor_number__isnull', True), ('valor_text__isnull', False), ('valor_boolean__isnull', True), ('valor_json__isnull', True)), models.Q(('valor_number__isnull', True), ('valor_text__isnull', True), ('valor_boolean__isnull', False), ('valor_json__isnull', True)), models.Q(('valor_number__isnull', True), ('valor_text__isnull', True), ('valor_boolean__isnull', True), ('valor_json__isnull', False)), _connector='OR'), name='valor_unico_tipo')],
                'unique_together': {('medicion', 'campo')},
            },
        ),
        migrations.AddIndex(
            model_name='formulario',
            index=models.Index(fields=['paciente'], name='idx_formulario_paciente'),
        ),
        migrations.AddIndex(
            model_name='formulario',
            index=models.Index(fields=['aseguradora'], name='idx_formulario_aseguradora'),
        ),
        migrations.AddConstraint(
            model_name='formulario',
            constraint=models.CheckConstraint(condition=models.Q(('num_hoja__gt', 0)), name='num_hoja_positivo'),
        ),
        migrations.AddConstraint(
            model_name='formulario',
            constraint=models.CheckConstraint(condition=models.Q(('edad_snapshot__gte', 0), ('edad_snapshot__isnull', True), _connector='OR'), name='edad_snapshot_no_negativa'),
        ),
        migrations.AddConstraint(
            model_name='formulario',
            constraint=models.CheckConstraint(condition=models.Q(('edad_gestion__gte', 0), ('edad_gestion__isnull', True), _connector='OR'), name='edad_gestion_no_negativa'),
        ),
        migrations.AddConstraint(
            model_name='formulario',
            constraint=models.CheckConstraint(condition=models.Q(('n_controles_prenatales__gte', 0), ('n_controles_prenatales__isnull', True), _connector='OR'), name='n_controles_no_negativo'),
        ),
        migrations.AlterUniqueTogether(
            name='formulario',
            unique_together={('codigo', 'version', 'num_hoja')},
        ),
        migrations.AddIndex(
            model_name='parametro',
            index=models.Index(fields=['item'], name='idx_parametro_item'),
        ),
        migrations.AlterUniqueTogether(
            name='parametro',
            unique_together={('item', 'codigo')},
        ),
        migrations.AddIndex(
            model_name='medicion',
            index=models.Index(fields=['formulario', 'parametro', 'tomada_en'], name='idx_medicion_form_param_time'),
        ),
        migrations.AlterUniqueTogether(
            name='medicion',
            unique_together={('formulario', 'parametro', 'tomada_en')},
        ),
        migrations.AlterUniqueTogether(
            name='formularioitemparametro',
            unique_together={('formulario', 'parametro')},
        ),
        migrations.AlterUniqueTogether(
            name='campoparametro',
            unique_together={('parametro', 'codigo')},
        ),
    ]
