# Generated by Django 5.2.9 on 2025-12-18 03:34

from django.db import migrations


def create_aseguradoras(apps, schema_editor):
    """Crear las aseguradoras principales"""
    Aseguradora = apps.get_model('clinico', 'Aseguradora')
    
    aseguradoras_data = [
        'Sura EPS',
        'Nueva EPS',
        'Sanitas',
        'Famisanar',
        'Coosalud',
        'Mutual SER',
        'Emssanar'
    ]

    for nombre_aseguradora in aseguradoras_data:
        Aseguradora.objects.get_or_create(nombre=nombre_aseguradora)


def reverse_aseguradoras(apps, schema_editor):
    """Eliminar las aseguradoras creadas"""
    Aseguradora = apps.get_model('clinico', 'Aseguradora')
    
    aseguradoras_nombres = [
        'Sura EPS',
        'Nueva EPS', 
        'Sanitas',
        'Famisanar',
        'Coosalud',
        'Mutual SER',
        'Emssanar'
    ]
    
    Aseguradora.objects.filter(nombre__in=aseguradoras_nombres).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0003_seed_clinico_data'),
    ]

    operations = [
        migrations.RunPython(
            create_aseguradoras,
            reverse_code=reverse_aseguradoras,
        ),
    ]
