# Generated by Django 5.2.9 on 2025-12-18 04:27

from django.db import migrations
from datetime import date


def create_pacientes(apps, schema_editor):
    """Crear pacientes de ejemplo"""
    Paciente = apps.get_model('clinico', 'Paciente')
    
    pacientes_data = [
        {
            'num_historia_clinica': 'HC001234',
            'num_identificacion': '1234567890',
            'nombres': 'María Fernanda González García',
            'fecha_nacimiento': date(1990, 5, 15),
            'tipo_sangre': 'O+'
        },
        {
            'num_historia_clinica': 'HC002345',
            'num_identificacion': '9876543210',
            'nombres': 'Ana Sofía Rodríguez Martínez',
            'fecha_nacimiento': date(1995, 8, 22),
            'tipo_sangre': 'A+'
        },
        {
            'num_historia_clinica': 'HC003456',
            'num_identificacion': '5555666677',
            'nombres': 'Laura Patricia Ramírez López',
            'fecha_nacimiento': date(1988, 12, 10),
            'tipo_sangre': 'B+'
        }
    ]
    
    for paciente_data in pacientes_data:
        Paciente.objects.get_or_create(
            num_identificacion=paciente_data['num_identificacion'],
            defaults=paciente_data
        )


def reverse_pacientes(apps, schema_editor):
    """Eliminar los pacientes creados"""
    Paciente = apps.get_model('clinico', 'Paciente')
    
    nums_identificacion = ['1234567890', '9876543210', '5555666677']
    Paciente.objects.filter(num_identificacion__in=nums_identificacion).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0004_seed_aseguradoras'),
    ]

    operations = [
        migrations.RunPython(
            create_pacientes,
            reverse_code=reverse_pacientes,
        ),
    ]
