# Generated by Django 5.2.9 on 2025-12-18

from django.db import migrations
from django.utils import timezone
from datetime import date


def create_formularios(apps, schema_editor):
    """Crear formularios de ejemplo relacionados con los pacientes y aseguradoras existentes"""
    Paciente = apps.get_model('clinico', 'Paciente')
    Aseguradora = apps.get_model('clinico', 'Aseguradora')
    Formulario = apps.get_model('clinico', 'Formulario')
    Item = apps.get_model('clinico', 'Item')
    Parametro = apps.get_model('clinico', 'Parametro')
    FormularioItemParametro = apps.get_model('clinico', 'FormularioItemParametro')

    # Obtener pacientes creados en la migración anterior
    p1 = Paciente.objects.filter(num_identificacion='1234567890').first()
    p2 = Paciente.objects.filter(num_identificacion='9876543210').first()
    p3 = Paciente.objects.filter(num_identificacion='5555666677').first()

    # Obtener aseguradoras
    a_sura = Aseguradora.objects.filter(nombre='Sura EPS').first()
    a_nueva = Aseguradora.objects.filter(nombre='Nueva EPS').first()
    a_sanitas = Aseguradora.objects.filter(nombre='Sanitas').first()

    # Datos de los formularios
    formularios_data = [
        {
            'codigo': 'FRSPA-022',
            'version': '01',
            'fecha_elabora': date(2025, 12, 18),
            'num_hoja': 1,
            'paciente': p1,
            'aseguradora': a_sura,
            'diagnostico': 'Trabajo de parto fase activa',
            'edad_snapshot': 35,
            'edad_gestion': 39,
            'estado': 'g',
            'n_controles_prenatales': 8,
            'responsable': 'Dr. Ricardo Mendoza'
        },
        {
            'codigo': 'FRSPA-022',
            'version': '01',
            'fecha_elabora': date(2025, 12, 17),
            'num_hoja': 1,
            'paciente': p2,
            'aseguradora': a_nueva,
            'diagnostico': 'Primigestante en trabajo de parto',
            'edad_snapshot': 30,
            'edad_gestion': 40,
            'estado': 'p',
            'n_controles_prenatales': 10,
            'responsable': 'Dra. Claudia Rivera'
        },
        {
            'codigo': 'FRSPA-022',
            'version': '01',
            'fecha_elabora': date(2025, 12, 16),
            'num_hoja': 1,
            'paciente': p3,
            'aseguradora': a_sanitas,
            'diagnostico': 'Embarazo prolongado - Inducción',
            'edad_snapshot': 37,
            'edad_gestion': 41,
            'estado': 'c',
            'n_controles_prenatales': 6,
            'responsable': 'Dr. Sergio Torres'
        }
    ]

    # Obtener todos los items y parámetros para asociarlos a los formularios
    items = Item.objects.all()
    
    for f_data in formularios_data:
        if f_data['paciente']: # Solo si el paciente existe
            f, created = Formulario.objects.get_or_create(
                paciente=f_data['paciente'],
                fecha_elabora=f_data['fecha_elabora'],
                num_hoja=f_data['num_hoja'],
                defaults=f_data
            )
            
            if created:
                # Asociar todos los parámetros disponibles al formulario
                # Esto es necesario para que aparezcan en el grid del formulario
                for item in items:
                    parametros = Parametro.objects.filter(item=item)
                    for param in parametros:
                        FormularioItemParametro.objects.get_or_create(
                            formulario=f,
                            item=item,
                            parametro=param,
                            defaults={'requerido': False}
                        )


def reverse_formularios(apps, schema_editor):
    """Eliminar los formularios creados"""
    Formulario = apps.get_model('clinico', 'Formulario')
    # Eliminamos por los responsables específicos de este seed
    responsables = ['Dr. Ricardo Mendoza', 'Dra. Claudia Rivera', 'Dr. Sergio Torres']
    Formulario.objects.filter(responsable__in=responsables).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0005_seed_pacientes'),
    ]

    operations = [
        migrations.RunPython(
            create_formularios,
            reverse_code=reverse_formularios,
        ),
    ]

