# Generated by Django 5.2.9 on 2025-12-18

from django.db import migrations
from django.utils import timezone
from datetime import datetime, timedelta


def create_mediciones_ejemplo(apps, schema_editor):
    """Crear mediciones y sus valores para los formularios de prueba"""
    Formulario = apps.get_model('clinico', 'Formulario')
    Parametro = apps.get_model('clinico', 'Parametro')
    CampoParametro = apps.get_model('clinico', 'CampoParametro')
    Medicion = apps.get_model('clinico', 'Medicion')
    MedicionValor = apps.get_model('clinico', 'MedicionValor')

    # Obtener formularios existentes (creados en la migración 0006)
    formularios = Formulario.objects.all()
    
    if not formularios.exists():
        return

    # Definir la hora base para las mediciones (hace 2 horas)
    ahora = timezone.now()
    hora_medicion_1 = ahora - timedelta(hours=2)
    hora_medicion_2 = ahora - timedelta(hours=1)

    for f in formularios:
        # --- 1. MEDICIÓN DE TENSIÓN ARTERIAL (Múltiples campos) ---
        param_ta = Parametro.objects.filter(codigo='TENSION_ART').first()
        if param_ta:
            m_ta = Medicion.objects.create(
                formulario=f,
                parametro=param_ta,
                tomada_en=hora_medicion_1,
                observacion="Control rutinario"
            )
            
            # Valores para TA (Sistólica y Diastólica)
            campo_sis = CampoParametro.objects.filter(parametro=param_ta, codigo='SISTOLICA').first()
            campo_dia = CampoParametro.objects.filter(parametro=param_ta, codigo='DIASTOLICA').first()
            
            if campo_sis:
                MedicionValor.objects.create(medicion=m_ta, campo=campo_sis, valor_number=120.0)
            if campo_dia:
                MedicionValor.objects.create(medicion=m_ta, campo=campo_dia, valor_number=80.0)

        # --- 2. MEDICIÓN DE FRECUENCIA CARDIACA (Campo único numérico) ---
        param_fc = Parametro.objects.filter(codigo='FREC_CARD').first()
        if param_fc:
            m_fc = Medicion.objects.create(
                formulario=f,
                parametro=param_fc,
                tomada_en=hora_medicion_1
            )
            
            campo_valor = CampoParametro.objects.filter(parametro=param_fc, codigo='VALOR').first()
            if campo_valor:
                MedicionValor.objects.create(medicion=m_fc, campo=campo_valor, valor_number=75.0)

        # --- 3. MEDICIÓN DE TACTO VAGINAL - DILATACIÓN (Otra hora) ---
        param_dil = Parametro.objects.filter(codigo='DILATACION').first()
        if param_dil:
            m_dil = Medicion.objects.create(
                formulario=f,
                parametro=param_dil,
                tomada_en=hora_medicion_2
            )
            
            campo_val_dil = CampoParametro.objects.filter(parametro=param_dil, codigo='VALOR').first()
            if campo_val_dil:
                MedicionValor.objects.create(medicion=m_dil, campo=campo_val_dil, valor_number=4.0)

        # --- 4. MEDICIÓN DE LÍQUIDO AMNIÓTICO (Campo de texto) ---
        param_liq = Parametro.objects.filter(codigo='LIQ_AMNIOTICO').first()
        if param_liq:
            m_liq = Medicion.objects.create(
                formulario=f,
                parametro=param_liq,
                tomada_en=hora_medicion_2
            )
            
            campo_desc = CampoParametro.objects.filter(parametro=param_liq, codigo='DESCRIPCION').first()
            if campo_desc:
                MedicionValor.objects.create(medicion=m_liq, campo=campo_desc, valor_text="Claro, sin olor")


def reverse_mediciones(apps, schema_editor):
    """Eliminar las mediciones creadas"""
    Medicion = apps.get_model('clinico', 'Medicion')
    Medicion.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0006_seed_formularios'),
    ]

    operations = [
        migrations.RunPython(
            create_mediciones_ejemplo,
            reverse_code=reverse_mediciones,
        ),
    ]

