# Generated by Django 5.2.10 on 2026-03-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0007_seed_mediciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmaPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_id', models.IntegerField()),
                ('formulario_id', models.IntegerField(blank=True, null=True)),
                ('template_huella', models.TextField(blank=True, null=True)),
                ('imagen_huella', models.ImageField(blank=True, null=True, upload_to='huellas/')),
                ('imagen_firma', models.ImageField(blank=True, null=True, upload_to='firmas/')),
                ('usuario', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'firma_paciente',
                'ordering': ['-fecha'],
            },
        ),
    ]
