# Generated by Django 5.2.10 on 2026-03-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0008_firmapaciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Huella',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_id', models.CharField(max_length=50)),
                ('formulario_id', models.CharField(blank=True, max_length=50, null=True)),
                ('template', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='huellas_biometricas/')),
                ('imagen_firma', models.ImageField(blank=True, null=True, upload_to='firmas/')),
                ('usuario', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'huella',
                'ordering': ['-fecha'],
            },
        ),
        migrations.DeleteModel(
            name='FirmaPaciente',
        ),
    ]
