# Generated by Django 5.2.11 on 2026-03-17 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0009_huella_delete_firmapaciente'),
        ('obstetricia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='atencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formularios_trabajoparto', to='obstetricia.atencionparto'),
        ),
    ]
