# Generated by Django 5.2.11 on 2026-03-18 19:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0010_formulario_atencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
