# Generated by Django 5.2.11 on 2026-07-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0011_formulario_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='abortos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Abortos (A)'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='cesareas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cesáreas (C)'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='gestas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Gestas (G)'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='partos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Partos (P)'),
        ),
    ]
