# Generated by Django 5.2.11 on 2026-09-14 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0014_fix_tipo_valor_frecuencia_duracion_etc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Huella',
        ),
    ]
