# Generated by Django 5.2.11 on 2026-09-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0015_delete_huella'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicion',
            name='responsable',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
