"""
Django settings for sistema_obstetrico project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import socket
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carga variables de un archivo .env (no versionado) si existe, ej. DJANGO_SECRET_KEY,
# DJANGO_DEBUG, REQUIRE_LOGIN, DGEMPRES03_*. Ver .env.example para la lista completa.
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
from django.core.exceptions import ImproperlyConfigured

# SECURITY WARNING: don't run with debug turned on in production!
# Por defecto False (seguro por defecto); poner DJANGO_DEBUG=True solo en desarrollo local.
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

# SECURITY WARNING: keep the secret key used in production secret!
# Debe venir SIEMPRE de la variable de entorno DJANGO_SECRET_KEY.
# 2026-09-10: en producción (DEBUG=False) ahora es OBLIGATORIA -- si falta, el
# proceso no arranca (falla claro y temprano) en vez de usar en silencio una
# clave conocida y publicada. El valor de respaldo solo aplica en DEBUG=True,
# para que un checkout nuevo sin .env todavía configurado no truene al correr
# `manage.py`.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-giplfuu5j2$k!p@9uqs9lncczcv=r5hd&!)v1r*+)ihh27-%ar'
    else:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY es obligatoria cuando DJANGO_DEBUG=False. "
            "Genere una clave única para este entorno y póngala en el .env."
        )

# Exige inicio de sesión en todo el sistema. Poner REQUIRE_LOGIN=False en .env únicamente si
# esta app queda temporalmente detrás de otra aplicación que ya controla el login.
REQUIRE_LOGIN = os.environ.get('REQUIRE_LOGIN', 'True') == 'True'

# Hosts permitidos.
# 2026-09-10: se agregó la variable DJANGO_ALLOWED_HOSTS (lista separada por
# comas, ej. "salapartos.hospital.local,10.20.30.40") para producción, sin
# tocar código. Si NO se define, el comportamiento es EXACTAMENTE el de antes:
#   - DEBUG=True  -> ['*']  (cómodo para tablets/PCs en la red local de dev)
#   - DEBUG=False -> ['localhost', '127.0.0.1']
_ALLOWED = os.environ.get('DJANGO_ALLOWED_HOSTS', '').strip()
if _ALLOWED:
    ALLOWED_HOSTS = [h.strip() for h in _ALLOWED.split(',') if h.strip()]
elif DEBUG:
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# Orígenes CSRF confiables para que la tablet pueda hacer POST (formularios, API).
# Evita depender de una IP fija cuando el equipo cambia de red.

def _get_local_ip():
    """Obtiene la IP local para añadirla a CSRF_TRUSTED_ORIGINS."""
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(('8.8.8.8', 80))
        ip = s.getsockname()[0]
        s.close()
        return ip
    except Exception:
        return None

_CSRF_EXTRA = os.environ.get('CSRF_TRUSTED_ORIGIN', '').strip()
# Puertos con los que se ha corrido `runserver` en este proyecto (backend y frontend
# separados según el equipo). Se listan todos para no tener que recordar actualizar
# este archivo cada vez que se cambia el puerto de arranque.
_DEV_PORTS = ['8000', '8001', '8002']
_DEV_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0']
CSRF_TRUSTED_ORIGINS = [
    f'http://{host}:{port}' for host in _DEV_HOSTS for port in _DEV_PORTS
]
_local_ip = _get_local_ip()
if _local_ip:
    CSRF_TRUSTED_ORIGINS += [f'http://{_local_ip}:{port}' for port in _DEV_PORTS]
if _CSRF_EXTRA:
    CSRF_TRUSTED_ORIGINS.append(_CSRF_EXTRA)


# ---------------------------------------------------------------------------
# Seguridad de transporte y de sesión
# 2026-09-10 -- endurecimiento de bajo impacto para producción, SIN cambiar
# el comportamiento en desarrollo (`runserver` sobre HTTP sigue funcionando
# igual). Todo lo "duro" está apagado por defecto y se enciende solo por
# variable de entorno cuando el entorno de verdad tenga HTTPS.
# ---------------------------------------------------------------------------

# Poner HTTPS_ENABLED=True en el .env SOLO cuando el sitio se sirva por HTTPS
# (típicamente detrás de un proxy inverso: Nginx, IIS, Traefik...). Mientras
# esté en False (default), nada de esto aplica y el login por HTTP local no
# se ve afectado.
_HTTPS_ENABLED = os.environ.get('HTTPS_ENABLED', 'False') == 'True'

# Cookies de sesión/CSRF: siempre HttpOnly + SameSite=Lax (ya eran el default
# de Django, se dejan explícitos). El flag Secure se activa solo con HTTPS
# real, porque marcar Secure sobre HTTP haría que el navegador NO mande la
# cookie y el login quedaría roto en desarrollo.
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = _HTTPS_ENABLED
CSRF_COOKIE_SECURE = _HTTPS_ENABLED

if _HTTPS_ENABLED:
    # Redirige HTTP -> HTTPS. Requiere que el proxy inverso mande la cabecera
    # X-Forwarded-Proto correctamente; con SECURE_PROXY_SSL_HEADER, Django
    # confía en ella para saber que la petición original sí venía por HTTPS
    # (evita un bucle de redirección infinito detrás del proxy).
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # HSTS se deja pendiente a propósito: una vez el navegador lo cachea es
    # difícil de revertir si HTTPS llega a fallar. Activarlo (SECURE_HSTS_*)
    # solo cuando HTTPS lleve tiempo estable en producción.

# Duración de la sesión.
# 2026-09-10 -- HALLAZGO: el default de Django es 1209600 s (14 días), muy
# largo para estaciones compartidas de sala de partos. Ahora es configurable
# por entorno con SESSION_HORAS. El DEFAULT SIGUE SIENDO 14 días (336 h) =
# comportamiento actual EXACTO, para no cambiar nada sin querer en pruebas.
# Recomendación para producción: SESSION_HORAS=24 (cubre un turno largo con
# relevo; una sesión olvidada muere en 24 h en vez de 2 semanas).
try:
    _SESSION_HORAS = int(os.environ.get('SESSION_HORAS', '336'))
except ValueError:
    _SESSION_HORAS = 336
SESSION_COOKIE_AGE = _SESSION_HORAS * 3600


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',

    'meows',
    'frecuenciafetal',
    'trabajoparto',
    'obstetriciaunificador',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sistema_obstetrico.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sistema_obstetrico.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        # Valores por defecto = cómo corre hoy fuera de Docker: SQL Server
        # Express de esta misma máquina, con autenticación de Windows
        # (USER/PASSWORD vacíos → mssql-django usa Trusted_Connection).
        #
        # Dentro de un contenedor Docker esos valores por defecto NO sirven:
        # "localhost" ahí es el propio contenedor (no esta máquina), y la
        # autenticación de Windows no existe en Linux. Para correr en Docker,
        # definir en el .env (pasado con `docker run --env-file .env`):
        #   DB_LOCAL_HOST=host.docker.internal
        #   DB_LOCAL_PORT=<puerto TCP fijo de la instancia, ver nota abajo>
        #   DB_LOCAL_USER=<login SQL, no de Windows>
        #   DB_LOCAL_PASSWORD=<password de ese login>
        # Requiere antes, en SQL Server Configuration Manager (una sola vez):
        #   1) Habilitar el protocolo TCP/IP de la instancia SQLEXPRESS y
        #      fijarle un puerto estático (por defecto usa uno dinámico vía
        #      el servicio SQL Browser, que un contenedor no resuelve bien).
        #   2) Habilitar "SQL Server and Windows Authentication mode" (modo
        #      mixto) y crear un login SQL con permisos sobre unificada_partos.
        #   3) Reiniciar el servicio SQL Server y permitir ese puerto en el
        #      Firewall de Windows.
        # Con DB_LOCAL_HOST/PORT así, se conecta directo por TCP y ya no hace
        # falta la sintaxis "HOST\SQLEXPRESS" (que depende del SQL Browser).
        # "or" en vez de sólo el default de .get(): así, si el .env real llega
        # a tener la línea presente pero vacía (en vez de no tenerla), sigue
        # cayendo al valor nativo de siempre en lugar de romper el arranque.
        'NAME': os.environ.get('DB_LOCAL_NAME') or 'unificada_partos',
        'USER': os.environ.get('DB_LOCAL_USER', ''),
        'PASSWORD': os.environ.get('DB_LOCAL_PASSWORD', ''),
        'HOST': os.environ.get('DB_LOCAL_HOST') or r'localhost\SQLEXPRESS',
        'PORT': os.environ.get('DB_LOCAL_PORT', ''),
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
            'extra_params': 'Encrypt=no;TrustServerCertificate=yes',
        },
    },

    'readonly': {  # 🔵 BD externa (NO TOCAR la lógica de solo-lectura)
        # Credenciales SIEMPRE desde variables de entorno (.env) — nunca hardcodeadas.
        # Ver .env.example para las claves DGEMPRES_NEXUS_USER/PASSWORD/HOST/NAME/PORT.
        #
        # 2026-09-08: NAME y PORT ahora también vienen de .env (antes NAME estaba
        # fijo en "DGEMPRES_NEXUS" en este archivo). Motivo: mientras se validan
        # los 2 campos nuevos (Nivel de Conciencia, % O2) con la jefe de sala de
        # partos, esta conexión debe apuntar TEMPORALMENTE a la base de pruebas
        # donde Dinámica realmente corre (DGEMPRES01 en 172.20.100.188) en vez
        # de a DGEMPRES_NEXUS (172.20.100.209) — cambiar solo el .env, sin tocar
        # código, y así también es más simple/seguro volver a producción después.
        'ENGINE': 'mssql',
        'NAME': os.environ.get('DGEMPRES_NEXUS_NAME') or 'DGEMPRES_NEXUS',
        'USER': os.environ.get('DGEMPRES_NEXUS_USER', ''),
        'PASSWORD': os.environ.get('DGEMPRES_NEXUS_PASSWORD', ''),
        'HOST': os.environ.get('DGEMPRES_NEXUS_HOST', ''),
        'PORT': os.environ.get('DGEMPRES_NEXUS_PORT') or '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
            # 2026-09-09 -- hallazgo "dependencia de disponibilidad de
            # Dinámica": sin esto, si el servidor de Dinámica no responde
            # (apagado, red caída, etc.), el intento de conexión se quedaba
            # colgado con el timeout por defecto del driver (bastante largo),
            # dejando la pantalla de login congestionada varios segundos
            # antes de fallar. "Connection Timeout" (segundos) solo limita
            # cuánto se espera para establecer la conexión -- no afecta el
            # tiempo permitido para que una consulta ya conectada termine.
            'extra_params': 'Encrypt=yes;TrustServerCertificate=yes;Connection Timeout=5',
        },
    },
}

# 2026-09-10 -- HALLAZGO DE SEGURIDAD "no afectar la BD de Dinámica ni en
# pruebas ni en producción": meows/db_router.py ya traía una clase
# ReadonlyRouter cuyo propio comentario decía "Bloquea migraciones en
# 'readonly'", pero nunca se había registrado aquí -- sin esta línea, Django
# no sabe que ese router existe, así que esa protección NUNCA estuvo activa
# realmente (era una falsa sensación de seguridad). Su allow_migrate()
# devuelve False para CUALQUIER app si db == 'readonly', así que a partir de
# ahora un `manage.py migrate --database=readonly` (a mano o por error) no
# podría crear/alterar/borrar nada ahí, sin importar qué app se intente
# migrar -- capa adicional a que ya ningún modelo mapeado a tablas de
# Dinámica es managed=True, y a que ninguna consulta del proyecto escribe en
# 'readonly' (ver auditoría 2026-09-10, sin una sola sentencia INSERT/UPDATE/
# DELETE/CREATE/ALTER/DROP contra esa conexión en todo el repositorio).
DATABASE_ROUTERS = ['meows.db_router.ReadonlyRouter']


# Backends de autenticación: primero se intenta DGH (Dinámica Gerencial, valida contra la
# BD hospitalaria externa y llena request.session['dgh_info']); ModelBackend queda como
# respaldo para usuarios nativos de Django (ej. admin) que no existen en DGH.
AUTHENTICATION_BACKENDS = [
    'frecuenciafetal.auth_dgh.DGHBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-co'

# Toda la app opera en el hospital, en Colombia (UTC-5, sin horario de verano).
# Con 'UTC' aquí, cualquier datetime "naive" (sin zona horaria explícita) que
# llegue de Dinámica o que digite el personal se interpretaba como si YA fuera
# UTC, desfasando 5 horas los cálculos de "hace X tiempo" contra la hora real
# (aunque la hora en pantalla se veía bien, porque no hay conversión visual
# de por medio). Con 'America/Bogota', Django interpreta correctamente esos
# datetimes naive como hora de Colombia.
TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
    BASE_DIR / "trabajoparto/static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = '/login/'

# Si REQUIRE_LOGIN es False (ver arriba), la API se comporta igual que hoy (sin login) —
# pensado para integrar esta app temporalmente detrás de otra que ya controle el acceso.
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated'
        if REQUIRE_LOGIN else
        'rest_framework.permissions.AllowAny'
    ],
}


# ---------------------------------------------------------------------------
# Logging
# 2026-09-10 -- antes no había NADA configurado: los mensajes de la app iban a
# `print()` sueltos (ver auth_dgh.py). Ahora hay un logger con salida a
# consola (stdout), que es justo lo que un contenedor Docker espera: se ven
# con `docker compose logs web` y los recoge cualquier recolector estándar.
# No se escribe a archivo a propósito (evita temas de rutas/permisos/rotación
# dentro del contenedor).
#
# IMPORTANTE: nunca registrar contraseñas, hashes, tokens, credenciales de BD
# ni datos clínicos de pacientes. Los loggers de la app (ej.
# 'frecuenciafetal.auth') solo emiten mensajes tipo "Dinámica no disponible",
# "usuario no encontrado", "error validando usuario".
_LOG_LEVEL = os.environ.get('DJANGO_LOG_LEVEL', 'INFO').upper()
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        # Loggers propios de la app (autenticación / integración con Dinámica).
        'frecuenciafetal': {
            'handlers': ['console'],
            'level': _LOG_LEVEL,
            'propagate': False,
        },
        # Errores del servidor Django (500, etc.): que se vean, sin pedir DEBUG.
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}
