# Generated by Django 4.2.28 on 2026-02-23 13:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlRecienNacido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_nacimiento', models.TimeField(verbose_name='Hora de Nacimiento')),
                ('pasa_uci_neonatal', models.BooleanField(default=False, verbose_name='Pasa a UCI Neonatal')),
                ('causa_uci', models.TextField(blank=True, null=True, verbose_name='Causa UCI')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('I', 'Indeterminado')], max_length=1)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(7000)], verbose_name='Peso (g)')),
                ('talla', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(70)], verbose_name='Talla (cm)')),
                ('pc', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Perímetro Cefálico (cm)')),
                ('pt', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Perímetro Torácico (cm)')),
                ('p_abd', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Perímetro Abdominal (cm)')),
                ('apgar_1min', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='APGAR 1 minuto')),
                ('apgar_5min', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='APGAR 5 minutos')),
                ('apgar_10min', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='APGAR 10 minutos')),
                ('tsh', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='TSH')),
                ('hemoclasificacion', models.CharField(blank=True, max_length=10, null=True, verbose_name='Hemoclasificación')),
                ('vacuna_hb', models.BooleanField(default=False, verbose_name='Vacuna HB')),
                ('vacuna_bcg', models.BooleanField(default=False, verbose_name='Vacuna BCG')),
                ('caracteristicas_liquido_amniotico', models.TextField(blank=True, null=True, verbose_name='Características del Líquido Amniótico')),
                ('lavado_gastrico', models.BooleanField(default=False, verbose_name='Lavado Gástrico')),
                ('lavado_elimina', models.BooleanField(default=False, verbose_name='Elimina')),
                ('meconio', models.BooleanField(default=False, verbose_name='Meconio')),
                ('oximetria_nacimiento_preductal', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Oximetría al Nacimiento Preductal (%)')),
                ('oximetria_nacimiento_posductal', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Oximetría al Nacimiento Posductal (%)')),
                ('oximetria_12h_preductal', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Oximetría 12h Preductal (%)')),
                ('oximetria_12h_posductal', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Oximetría 12h Posductal (%)')),
                ('ta_msd', models.CharField(blank=True, max_length=20, null=True, verbose_name='TA MSD')),
                ('ta_msi', models.CharField(blank=True, max_length=20, null=True, verbose_name='TA MSI')),
                ('ta_mid', models.CharField(blank=True, max_length=20, null=True, verbose_name='TA MID')),
                ('ta_miiz', models.CharField(blank=True, max_length=20, null=True, verbose_name='TA MIIZ')),
                ('neonato_atendido_por', models.CharField(blank=True, max_length=200, null=True)),
                ('valorado_pediatra', models.BooleanField(default=False, verbose_name='Valorado por Pediatra antes del Egreso')),
                ('huella_pie', models.ImageField(blank=True, null=True, upload_to='huellas_pie/%Y/%m/', verbose_name='Huella del Pie del Recién Nacido')),
                ('huella_pie_base64', models.TextField(blank=True, null=True, verbose_name='Huella del Pie (Base64)')),
            ],
            options={
                'verbose_name': 'Control del Recién Nacido',
            },
        ),
        migrations.CreateModel(
            name='RegistroPartoPaciente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_paciente', models.CharField(max_length=200, verbose_name='Nombre de la Paciente')),
                ('identificacion', models.CharField(max_length=50, verbose_name='Identificación')),
                ('edad_gestacional', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(45)], verbose_name='Edad Gestacional (semanas)')),
                ('gestas', models.PositiveSmallIntegerField(default=1, verbose_name='Gestas')),
                ('nombre_acompanante', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Acompañante en el Parto')),
                ('tipo_parto', models.CharField(blank=True, choices=[('VAGINAL', 'Vaginal'), ('INSTRUMENTADO', 'Instrumentado'), ('CESAREA', 'Cesárea')], max_length=20, null=True)),
                ('episiotomia', models.BooleanField(default=False, verbose_name='Episiotomía')),
                ('tipo_alumbramiento', models.CharField(blank=True, choices=[('ESPONTANEO', 'Espontáneo'), ('DIRIGIDO', 'Dirigido'), ('MANUAL', 'Manual')], max_length=20, null=True)),
                ('parto_atendido_por', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registro de Parto',
                'verbose_name_plural': 'Registros de Parto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GlucometriaRecienNacido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('resultado', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Resultado (mg/dL)')),
                ('control_rn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glucometrias', to='registros.controlreciennacido')),
            ],
            options={
                'verbose_name': 'Glucometría',
                'verbose_name_plural': 'Glucometrías',
                'ordering': ['hora'],
            },
        ),
        migrations.AddField(
            model_name='controlreciennacido',
            name='registro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='control_recien_nacido', to='registros.registropartopaciente'),
        ),
        migrations.CreateModel(
            name='ControlPostpartoInmediato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto_control', models.PositiveSmallIntegerField(verbose_name='Minuto del Control')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('tension_arterial', models.CharField(blank=True, max_length=20, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura (°C)')),
                ('pulso', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Pulso (lpm)')),
                ('respiracion', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Respiración (rpm)')),
                ('sangrado_vaginal', models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('ABUNDANTE', 'Abundante')], max_length=20, null=True)),
                ('involucion_uterina', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable', models.CharField(blank=True, max_length=200, null=True)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles_postparto', to='registros.registropartopaciente')),
            ],
            options={
                'verbose_name': 'Control Postparto Inmediato',
                'verbose_name_plural': 'Controles Postparto Inmediato',
                'ordering': ['fecha', 'hora'],
            },
        ),
        migrations.CreateModel(
            name='ControlFetocardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('fetocardia', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(250)], verbose_name='Fetocardia (lpm)')),
                ('responsable', models.CharField(max_length=200, verbose_name='Responsable')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles_fetocardia', to='registros.registropartopaciente')),
            ],
            options={
                'verbose_name': 'Control de Fetocardia',
                'verbose_name_plural': 'Controles de Fetocardia',
                'ordering': ['fecha', 'hora'],
            },
        ),
    ]
