# Generated by Django 4.2.28 on 2026-03-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_allow_blank_responsable_fetocardia'),
    ]

    operations = [
        migrations.CreateModel(
            name='HuellaBebe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bebe_id', models.IntegerField()),
                ('tipo', models.CharField(choices=[('derecho', 'Pie Derecho'), ('izquierdo', 'Pie Izquierdo')], max_length=20)),
                ('imagen', models.ImageField(upload_to='huellas_bebe/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
