# Generated by Django 4.2.28 on 2026-03-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_huellabebe'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropartopaciente',
            name='firma_responsable',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/%Y/%m/', verbose_name='Firma del Responsable'),
        ),
    ]
