# Generated by Django 4.2.28 on 2026-03-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_registropartopaciente_firma_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropartopaciente',
            name='fecha_hora_firma',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registropartopaciente',
            name='nombre_firma_responsable',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
