# Generated by Django 4.2.28 on 2026-03-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_registropartopaciente_fecha_hora_firma_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registropartopaciente',
            name='firma_responsable',
        ),
        migrations.RemoveField(
            model_name='registropartopaciente',
            name='nombre_firma_responsable',
        ),
        migrations.AddField(
            model_name='registropartopaciente',
            name='firma_paciente',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/', verbose_name='Firma de la Paciente'),
        ),
        migrations.AddField(
            model_name='registropartopaciente',
            name='nombre_firma_paciente',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre de la Paciente que firma'),
        ),
    ]
