# Generated by Django 4.2.28 on 2026-03-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_remove_registropartopaciente_firma_responsable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropartopaciente',
            name='firma_profesional_base64',
            field=models.TextField(blank=True, null=True, verbose_name='Firma del Profesional (Base64)'),
        ),
        migrations.AddField(
            model_name='registropartopaciente',
            name='profesional_identificacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registropartopaciente',
            name='profesional_nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registropartopaciente',
            name='profesional_tarjeta_pro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
