# Generated by Django 4.2.28 on 2026-03-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0007_registropartopaciente_firma_profesional_base64_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmaPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_id', models.IntegerField()),
                ('template_huella', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
