# Generated by Django 4.2.28 on 2026-03-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0008_firmapaciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmapaciente',
            name='usuario',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
