# Generated by Django 4.2.28 on 2026-03-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0009_firmapaciente_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmapaciente',
            name='imagen_huella',
            field=models.TextField(blank=True, null=True),
        ),
    ]
