# Generated by Django 4.2.28 on 2026-03-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0010_firmapaciente_imagen_huella'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmapaciente',
            name='formulario_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
