# Generated by Django 4.2.28 on 2026-03-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0011_firmapaciente_formulario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmapaciente',
            name='imagen_huella',
            field=models.ImageField(blank=True, null=True, upload_to='huellas/'),
        ),
    ]
