# Generated by Django 4.2.28 on 2026-03-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0012_alter_firmapaciente_imagen_huella'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmapaciente',
            name='formulario_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
