# Generated by Django 4.2.28 on 2026-03-11 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0013_alter_firmapaciente_formulario_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firmapaciente',
            name='formulario_id',
        ),
        migrations.AddField(
            model_name='firmapaciente',
            name='formulario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firmas', to='registros.registropartopaciente'),
        ),
    ]
