# Generated by Django 5.2.11 on 2026-03-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0014_remove_firmapaciente_formulario_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Huella',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_id', models.CharField(max_length=50, verbose_name='Identificación del Paciente')),
                ('huella', models.TextField(verbose_name='Template de la Huella')),
                ('imagen_huella', models.ImageField(blank=True, null=True, upload_to='huellas_biometricas/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(default='SYSTEM', max_length=100)),
            ],
            options={
                'verbose_name': 'Huella Biométrica',
                'verbose_name_plural': 'Huellas Biométricas',
                'ordering': ['-fecha'],
            },
        ),
    ]
