# Generated by Django 5.2.11 on 2026-03-11 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0015_huella'),
    ]

    operations = [
        migrations.RenameField(
            model_name='huella',
            old_name='paciente_id',
            new_name='documento',
        ),
        migrations.RenameField(
            model_name='huella',
            old_name='huella',
            new_name='template',
        ),
    ]
