# Generated by Django 5.2.11 on 2026-03-17 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obstetricia', '0001_initial'),
        ('registros', '0017_merge_0003_postparto_0016_huella'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropartopaciente',
            name='atencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_fetal', to='obstetricia.atencionparto'),
        ),
    ]
