# Generated by Django 5.2.11 on 2026-03-18 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obstetricia', '0002_allow_blank_paciente'),
        ('registros', '0018_registropartopaciente_atencion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistroPartoPaciente',
            new_name='RegistroParto',
        ),
    ]
