# Generated by Django 5.2.11 on 2026-07-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0019_rename_registropartopaciente_registroparto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroparto',
            name='edad_gestacional',
            field=models.PositiveSmallIntegerField(verbose_name='Edad Gestacional (semanas)'),
        ),
        migrations.AlterField(
            model_name='registroparto',
            name='firma_paciente',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/', verbose_name='Firma del Responsable'),
        ),
        migrations.AlterField(
            model_name='registroparto',
            name='nombre_firma_paciente',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Responsable que firma'),
        ),
    ]
