# Generated by Django 5.2.11 on 2026-07-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0020_alter_registroparto_edad_gestacional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlpostpartoinmediato',
            name='respiracion',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Respiración (rpm)'),
        ),
        migrations.AlterField(
            model_name='controlreciennacido',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso (g)'),
        ),
    ]
