# Generated by Django 5.2.11 on 2026-07-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0021_alter_controlpostpartoinmediato_respiracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlfetocardia',
            name='fetocardia',
            field=models.SmallIntegerField(verbose_name='Fetocardia (lpm)'),
        ),
        migrations.AlterField(
            model_name='controlpostpartoinmediato',
            name='cuantificacion_gravimetrica_vaginal',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cuantificación Gravimétrica Vaginal (g)'),
        ),
        migrations.AlterField(
            model_name='controlpostpartoinmediato',
            name='pulso',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Pulso (lpm)'),
        ),
        migrations.AlterField(
            model_name='controlpostpartoinmediato',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Temperatura (°C)'),
        ),
        migrations.AlterField(
            model_name='controlreciennacido',
            name='apgar_10min',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='APGAR 10 minutos'),
        ),
        migrations.AlterField(
            model_name='controlreciennacido',
            name='apgar_1min',
            field=models.SmallIntegerField(verbose_name='APGAR 1 minuto'),
        ),
        migrations.AlterField(
            model_name='controlreciennacido',
            name='apgar_5min',
            field=models.SmallIntegerField(verbose_name='APGAR 5 minutos'),
        ),
        migrations.AlterField(
            model_name='controlreciennacido',
            name='oximetria_12h_posductal',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Oximetría 12h Posductal (%)'),
        ),
        migrations.AlterField(
            model_name='controlreciennacido',
            name='oximetria_12h_preductal',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Oximetría 12h Preductal (%)'),
        ),
        migrations.AlterField(
            model_name='controlreciennacido',
            name='oximetria_nacimiento_posductal',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Oximetría al Nacimiento Posductal (%)'),
        ),
        migrations.AlterField(
            model_name='controlreciennacido',
            name='oximetria_nacimiento_preductal',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Oximetría al Nacimiento Preductal (%)'),
        ),
        migrations.AlterField(
            model_name='controlreciennacido',
            name='p_abd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Perímetro Abdominal (cm)'),
        ),
        migrations.AlterField(
            model_name='controlreciennacido',
            name='pc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Perímetro Cefálico (cm)'),
        ),
        migrations.AlterField(
            model_name='controlreciennacido',
            name='pt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Perímetro Torácico (cm)'),
        ),
        migrations.AlterField(
            model_name='controlreciennacido',
            name='talla',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Talla (cm)'),
        ),
        migrations.AlterField(
            model_name='controlreciennacido',
            name='tsh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='TSH'),
        ),
        migrations.AlterField(
            model_name='glucometriareciennacido',
            name='resultado',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Resultado (mg/dL)'),
        ),
        migrations.AlterField(
            model_name='registroparto',
            name='edad_gestacional',
            field=models.SmallIntegerField(verbose_name='Edad Gestacional (semanas)'),
        ),
        migrations.AlterField(
            model_name='registroparto',
            name='gestas',
            field=models.SmallIntegerField(default=1, verbose_name='Gestas'),
        ),
    ]
