# Generated by Django 5.2.11 on 2026-07-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0022_alter_controlfetocardia_fetocardia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlpostpartoinmediato',
            name='saturacion',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Saturación (%)'),
        ),
    ]
