# Generated by Django 5.2.11 on 2026-08-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0023_controlpostpartoinmediato_saturacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroparto',
            name='globo_seguridad',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal: útero firme y contraído, altura ±1cm del ombligo'), ('ALERTA', 'Alerta: útero blando, relajado o desviado (atonía)')], max_length=20, null=True, verbose_name='Globo de seguridad (evolución de la altura uterina)'),
        ),
        migrations.AddField(
            model_name='registroparto',
            name='sangrado_cuantificado_cc',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Sangrado cuantificado (c.c.)'),
        ),
        migrations.AddField(
            model_name='registroparto',
            name='sutura_heridas',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal: bordes afrontados, sin secreción, dolor tolerable'), ('HEMATOMA', 'Alerta: hematoma (masa violácea, tensa, dolor intenso)'), ('INFECCION', 'Alerta: infección (eritema, calor local, edema, secreción purulenta)')], max_length=20, null=True, verbose_name='Sutura y heridas (descarte de hematomas e infección)'),
        ),
    ]
