# Generated by Django 5.2.11 on 2026-08-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0024_registroparto_globo_seguridad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroparto',
            name='globo_seguridad',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal: útero firme y contraído, altura ±1cm del ombligo'), ('ALERTA', 'Alerta: útero blando, relajado o desviado (atonía), fondo uterino por encima del ombligo')], max_length=20, null=True, verbose_name='Globo de seguridad (evolución de la altura uterina)'),
        ),
        migrations.AlterField(
            model_name='registroparto',
            name='sutura_heridas',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal: bordes afrontados, sin secreción, dolor tolerable, sin cambios de coloración'), ('HEMATOMA', 'Alerta: hematoma (masa violácea, tensa, dolor intenso, rectal, vaginal, insoportable)'), ('INFECCION', 'Alerta: infección (eritema, calor local, edema, secreción purulenta)')], max_length=20, null=True, verbose_name='Sutura y heridas (descarte de hematomas e infección)'),
        ),
    ]
