# Generated by Django 5.2.11 on 2026-08-24 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0025_alter_registroparto_globo_seguridad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlSangrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto_control', models.PositiveSmallIntegerField(verbose_name='Minuto del control (cronograma 15/30/60)')),
                ('hora', models.TimeField(verbose_name='Hora del control')),
                ('cc', models.PositiveIntegerField(verbose_name='Sangrado cuantificado en este control (c.c.)')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles_sangrado', to='registros.registroparto')),
            ],
            options={
                'verbose_name': 'Control de Sangrado',
                'verbose_name_plural': 'Controles de Sangrado',
                'ordering': ['minuto_control'],
                'unique_together': {('registro', 'minuto_control')},
            },
        ),
    ]
