# Generated by Django 5.2.11 on 2026-09-10 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0026_controlsangrado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='huella',
            options={'verbose_name': 'Huella Biométrica', 'verbose_name_plural': 'Huellas Biométricas'},
        ),
        migrations.CreateModel(
            name='IntentoLoginFallido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Intento de login fallido',
                'verbose_name_plural': 'Intentos de login fallidos',
                'indexes': [models.Index(fields=['ip', 'creado'], name='registros_i_ip_74000b_idx')],
            },
        ),
    ]
