# Generated by Django 5.2.11 on 2026-09-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0027_alter_huella_options_intentologinfallido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firmapaciente',
            name='formulario',
        ),
        migrations.DeleteModel(
            name='Huella',
        ),
        migrations.DeleteModel(
            name='HuellaBebe',
        ),
        migrations.RemoveField(
            model_name='controlreciennacido',
            name='huella_pie',
        ),
        migrations.RemoveField(
            model_name='controlreciennacido',
            name='huella_pie_base64',
        ),
        migrations.RemoveField(
            model_name='registroparto',
            name='fecha_hora_firma',
        ),
        migrations.RemoveField(
            model_name='registroparto',
            name='firma_paciente',
        ),
        migrations.RemoveField(
            model_name='registroparto',
            name='firma_profesional_base64',
        ),
        migrations.AlterField(
            model_name='registroparto',
            name='nombre_firma_paciente',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Responsable del Registro'),
        ),
        migrations.DeleteModel(
            name='FirmaPaciente',
        ),
    ]
