# Generated by Django 5.2.11 on 2026-09-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0028_remove_firmapaciente_formulario_delete_huella_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroparto',
            name='hora_parto',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Parto'),
        ),
    ]
