# Generated by Django 5.2.11 on 2026-09-18 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0029_registroparto_hora_parto'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlsangrado',
            name='estado',
            field=models.CharField(blank=True, choices=[('NORMAL', 'NORMAL'), ('VIGILAR', 'VIGILAR'), ('ALERTA', 'ALERTA')], max_length=20, null=True, verbose_name='Estado del semáforo en este control'),
        ),
        migrations.CreateModel(
            name='ControlGlobo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto_control', models.PositiveSmallIntegerField(verbose_name='Minuto del control (cronograma 15/30/60)')),
                ('hora', models.TimeField(verbose_name='Hora del control')),
                ('estado', models.CharField(choices=[('NORMAL', 'Normal: útero firme y contraído, altura ±1cm del ombligo'), ('ALERTA', 'Alerta: útero blando, relajado o desviado (atonía), fondo uterino por encima del ombligo')], max_length=20, verbose_name='Estado del globo de seguridad en este control')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles_globo', to='registros.registroparto')),
            ],
            options={
                'verbose_name': 'Control de Globo de Seguridad',
                'verbose_name_plural': 'Controles de Globo de Seguridad',
                'ordering': ['minuto_control'],
                'unique_together': {('registro', 'minuto_control')},
            },
        ),
        migrations.CreateModel(
            name='ControlSutura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto_control', models.PositiveSmallIntegerField(verbose_name='Minuto del control (cronograma 15/30/60)')),
                ('hora', models.TimeField(verbose_name='Hora del control')),
                ('estado', models.CharField(choices=[('NORMAL', 'Normal: bordes afrontados, sin secreción, dolor tolerable, sin cambios de coloración'), ('HEMATOMA', 'Alerta: hematoma (masa violácea, tensa, dolor intenso, rectal, vaginal, insoportable)'), ('INFECCION', 'Alerta: infección (eritema, calor local, edema, secreción purulenta)')], max_length=20, verbose_name='Estado de sutura y heridas en este control')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles_sutura', to='registros.registroparto')),
            ],
            options={
                'verbose_name': 'Control de Sutura y Heridas',
                'verbose_name_plural': 'Controles de Sutura y Heridas',
                'ordering': ['minuto_control'],
                'unique_together': {('registro', 'minuto_control')},
            },
        ),
    ]
