# Generated by Django 5.2.11 on 2026-09-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0030_controlsangrado_estado_controlglobo_controlsutura'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroparto',
            name='desgarro',
            field=models.CharField(blank=True, choices=[('GRADO_I', 'Grado I'), ('GRADO_II', 'Grado II'), ('GRADO_III', 'Grado III'), ('GRADO_IV', 'Grado IV')], max_length=20, null=True, verbose_name='Desgarro'),
        ),
        migrations.AddField(
            model_name='registroparto',
            name='desgarro_subgrado',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=5, null=True, verbose_name='Subclasificación del desgarro Grado III (A/B/C)'),
        ),
        migrations.AlterField(
            model_name='controlglobo',
            name='estado',
            field=models.CharField(choices=[('UNIFORME', 'Uniforme'), ('LEVE', 'Leve'), ('CONTRAIDO', 'Contraído')], max_length=20, verbose_name='Estado del globo de seguridad en este control'),
        ),
        migrations.AlterField(
            model_name='registroparto',
            name='globo_seguridad',
            field=models.CharField(blank=True, choices=[('UNIFORME', 'Uniforme'), ('LEVE', 'Leve'), ('CONTRAIDO', 'Contraído')], max_length=20, null=True, verbose_name='Globo de seguridad (evolución de la altura uterina)'),
        ),
    ]
