# Generated by Django 5.2.11 on 2026-09-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0031_registroparto_desgarro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlglobo',
            name='estado',
            field=models.CharField(choices=[('NORMAL', 'Normal: útero firme y contraído'), ('ALERTA', 'Alerta: útero blando, relajado, atonía')], max_length=20, verbose_name='Estado del globo de seguridad en este control'),
        ),
        migrations.AlterField(
            model_name='registroparto',
            name='globo_seguridad',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal: útero firme y contraído'), ('ALERTA', 'Alerta: útero blando, relajado, atonía')], max_length=20, null=True, verbose_name='Globo de seguridad (evolución de la altura uterina)'),
        ),
    ]
