# Generated by Django 5.2.11 on 2026-09-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0032_alter_controlglobo_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlsutura',
            name='estado',
            field=models.CharField(choices=[('NORMAL', 'Normal: bordes afrontados, dolor tolerable, sin cambios de coloración'), ('HEMATOMA', 'Alerta: hematoma (masa violácea, tensa, dolor intenso)'), ('INFECCION', 'Alerta: (eritema, calor local, edema, secreción purulenta)')], max_length=20, verbose_name='Estado de sutura y heridas en este control'),
        ),
        migrations.AlterField(
            model_name='registroparto',
            name='sutura_heridas',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal: bordes afrontados, dolor tolerable, sin cambios de coloración'), ('HEMATOMA', 'Alerta: hematoma (masa violácea, tensa, dolor intenso)'), ('INFECCION', 'Alerta: (eritema, calor local, edema, secreción purulenta)')], max_length=20, null=True, verbose_name='Sutura y heridas (descarte de hematomas e infección)'),
        ),
    ]
