# Generated by Django 5.2.11 on 2026-09-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0033_alter_controlsutura_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroparto',
            name='completado_en',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Cerrado (Guardar Registro Completo)'),
        ),
        migrations.AddField(
            model_name='registroparto',
            name='completado_por',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cerrado por'),
        ),
    ]
