# Generated by Django 5.2.11 on 2026-09-28 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0034_registroparto_completado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlfetocardia',
            name='registrado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controlfetocardia',
            name='registrado_por',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='controlglobo',
            name='registrado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controlglobo',
            name='registrado_por',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='controlpostpartoinmediato',
            name='registrado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controlpostpartoinmediato',
            name='registrado_por',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='controlreciennacido',
            name='registrado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controlreciennacido',
            name='registrado_por',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='controlsangrado',
            name='registrado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controlsangrado',
            name='registrado_por',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='controlsutura',
            name='registrado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controlsutura',
            name='registrado_por',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='registroparto',
            name='creado_por',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Creado por'),
        ),
        migrations.CreateModel(
            name='ParticipacionRegistroParto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesional', models.CharField(max_length=255)),
                ('usuario', models.CharField(blank=True, default='', max_length=150)),
                ('primera_vez', models.DateTimeField()),
                ('ultima_vez', models.DateTimeField()),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='registros.registroparto')),
            ],
            options={
                'verbose_name': 'Participación en registro de parto',
                'verbose_name_plural': 'Participaciones en registros de parto',
                'ordering': ['primera_vez'],
                'unique_together': {('registro', 'profesional')},
            },
        ),
    ]
