# Generated by Django 5.2.11 on 2026-10-01 00:50

import frecuenciafetal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0035_firma_automatica_responsables'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlreciennacido',
            name='huella_pdf',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=frecuenciafetal.models._ruta_huella_rn, verbose_name='Huella plantar (PDF)'),
        ),
        migrations.AddField(
            model_name='controlreciennacido',
            name='huella_subida_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controlreciennacido',
            name='huella_subida_por',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='controlreciennacido',
            name='tsh_tomada',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='TSH tomada'),
        ),
        migrations.AlterField(
            model_name='controlreciennacido',
            name='apgar_1min',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='APGAR 1 minuto'),
        ),
        migrations.AlterField(
            model_name='controlreciennacido',
            name='apgar_5min',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='APGAR 5 minutos'),
        ),
        migrations.AlterField(
            model_name='controlreciennacido',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('I', 'Indeterminado')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='controlreciennacido',
            name='hora_nacimiento',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='controlreciennacido',
            name='lavado_elimina',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Elimina'),
        ),
        migrations.AlterField(
            model_name='controlreciennacido',
            name='lavado_gastrico',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Lavado Gástrico'),
        ),
        migrations.AlterField(
            model_name='controlreciennacido',
            name='meconio',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Meconio'),
        ),
        migrations.AlterField(
            model_name='controlreciennacido',
            name='pasa_uci_neonatal',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Pasa a UCI Neonatal'),
        ),
        migrations.AlterField(
            model_name='controlreciennacido',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso (g)'),
        ),
        migrations.AlterField(
            model_name='controlreciennacido',
            name='talla',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Talla (cm)'),
        ),
        migrations.AlterField(
            model_name='controlreciennacido',
            name='tsh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='TSH (resultado, sin uso en el formulario)'),
        ),
        migrations.AlterField(
            model_name='controlreciennacido',
            name='valorado_pediatra',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Valorado por Pediatra antes del Egreso'),
        ),
    ]
