# Generated by Django 5.2.11 on 2026-10-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0036_recien_nacido_huella_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlreciennacido',
            name='ta24_mid',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='TA 24 h MID'),
        ),
        migrations.AddField(
            model_name='controlreciennacido',
            name='ta24_miiz',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='TA 24 h MIIZ'),
        ),
        migrations.AddField(
            model_name='controlreciennacido',
            name='ta24_msd',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='TA 24 h MSD'),
        ),
        migrations.AddField(
            model_name='controlreciennacido',
            name='ta24_msi',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='TA 24 h MSI'),
        ),
        migrations.AddField(
            model_name='controlreciennacido',
            name='ta48_mid',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='TA 48 h MID'),
        ),
        migrations.AddField(
            model_name='controlreciennacido',
            name='ta48_miiz',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='TA 48 h MIIZ'),
        ),
        migrations.AddField(
            model_name='controlreciennacido',
            name='ta48_msd',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='TA 48 h MSD'),
        ),
        migrations.AddField(
            model_name='controlreciennacido',
            name='ta48_msi',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='TA 48 h MSI'),
        ),
    ]
