# Generated by Django 5.2.11 on 2026-10-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0037_recien_nacido_ta_24h_48h'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlreciennacido',
            name='fc_nacimiento',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Frecuencia cardiaca al nacimiento (lpm)'),
        ),
        migrations.AddField(
            model_name='controlreciennacido',
            name='tanac12_mid',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Al nacimiento: TA 12 h MID'),
        ),
        migrations.AddField(
            model_name='controlreciennacido',
            name='tanac12_miiz',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Al nacimiento: TA 12 h MIIZ'),
        ),
        migrations.AddField(
            model_name='controlreciennacido',
            name='tanac12_msd',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Al nacimiento: TA 12 h MSD'),
        ),
        migrations.AddField(
            model_name='controlreciennacido',
            name='tanac12_msi',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Al nacimiento: TA 12 h MSI'),
        ),
        migrations.AddField(
            model_name='controlreciennacido',
            name='tanac24_mid',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Al nacimiento: TA 24 h MID'),
        ),
        migrations.AddField(
            model_name='controlreciennacido',
            name='tanac24_miiz',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Al nacimiento: TA 24 h MIIZ'),
        ),
        migrations.AddField(
            model_name='controlreciennacido',
            name='tanac24_msd',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Al nacimiento: TA 24 h MSD'),
        ),
        migrations.AddField(
            model_name='controlreciennacido',
            name='tanac24_msi',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Al nacimiento: TA 24 h MSI'),
        ),
        migrations.AddField(
            model_name='controlreciennacido',
            name='tanac48_mid',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Al nacimiento: TA 48 h MID'),
        ),
        migrations.AddField(
            model_name='controlreciennacido',
            name='tanac48_miiz',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Al nacimiento: TA 48 h MIIZ'),
        ),
        migrations.AddField(
            model_name='controlreciennacido',
            name='tanac48_msd',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Al nacimiento: TA 48 h MSD'),
        ),
        migrations.AddField(
            model_name='controlreciennacido',
            name='tanac48_msi',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Al nacimiento: TA 48 h MSI'),
        ),
        migrations.AddField(
            model_name='controlreciennacido',
            name='tanac_mid',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='TA al nacimiento MID'),
        ),
        migrations.AddField(
            model_name='controlreciennacido',
            name='tanac_miiz',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='TA al nacimiento MIIZ'),
        ),
        migrations.AddField(
            model_name='controlreciennacido',
            name='tanac_msd',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='TA al nacimiento MSD'),
        ),
        migrations.AddField(
            model_name='controlreciennacido',
            name='tanac_msi',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='TA al nacimiento MSI'),
        ),
    ]
