# Generated by Django 5.2.11 on 2026-10-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0038_recien_nacido_ta_fc_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlglobo',
            name='estado',
            field=models.CharField(choices=[('NORMAL', 'Normal: útero firme y contraído'), ('ALERTA', 'Alerta: útero blando, relajado, atonía'), ('NO_APLICA', 'No aplica')], max_length=20, verbose_name='Estado del globo de seguridad en este control'),
        ),
        migrations.AlterField(
            model_name='controlsutura',
            name='estado',
            field=models.CharField(choices=[('NORMAL', 'Normal: bordes afrontados, dolor tolerable, sin cambios de coloración'), ('HEMATOMA', 'Alerta: hematoma (masa violácea, tensa, dolor intenso)'), ('INFECCION', 'Alerta: (eritema, calor local, edema, secreción purulenta)'), ('NO_APLICA', 'No aplica')], max_length=20, verbose_name='Estado de sutura y heridas en este control'),
        ),
        migrations.AlterField(
            model_name='registroparto',
            name='globo_seguridad',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal: útero firme y contraído'), ('ALERTA', 'Alerta: útero blando, relajado, atonía'), ('NO_APLICA', 'No aplica')], max_length=20, null=True, verbose_name='Globo de seguridad (evolución de la altura uterina)'),
        ),
        migrations.AlterField(
            model_name='registroparto',
            name='sutura_heridas',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal: bordes afrontados, dolor tolerable, sin cambios de coloración'), ('HEMATOMA', 'Alerta: hematoma (masa violácea, tensa, dolor intenso)'), ('INFECCION', 'Alerta: (eritema, calor local, edema, secreción purulenta)'), ('NO_APLICA', 'No aplica')], max_length=20, null=True, verbose_name='Sutura y heridas (descarte de hematomas e infección)'),
        ),
    ]
