# Generated by Django 5.2.11 on 2026-10-06 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0041_rn_glucometrias_no_aplica'),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioRegistroParto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(choices=[('fetocardia', 'Fetocardia'), ('parto', 'Características del parto'), ('vigilancia', 'Vigilancia posparto'), ('recien_nacido', 'Recién nacido')], max_length=20)),
                ('accion', models.CharField(choices=[('registro', 'Registró'), ('correccion', 'Corrigió'), ('eliminacion', 'Eliminó')], max_length=15)),
                ('detalle', models.CharField(help_text='Campo o control (sin valores).', max_length=255)),
                ('profesional', models.CharField(blank=True, default='', max_length=255)),
                ('usuario', models.CharField(blank=True, default='', max_length=150)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios', to='registros.registroparto')),
            ],
            options={
                'verbose_name': 'Cambio en registro de parto',
                'verbose_name_plural': 'Bitácora de cambios en registros de parto',
                'ordering': ['creado_en', 'id'],
                'indexes': [models.Index(fields=['registro', 'seccion'], name='registros_c_registr_5503cb_idx')],
            },
        ),
    ]
