# Generated by Django 5.2.11 on 2026-10-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0042_bitacora_cambios_registro_parto'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlsangrado',
            name='detalle',
            field=models.JSONField(blank=True, null=True, verbose_name='Detalle de materiales y pesajes'),
        ),
    ]
