# Generated by Django 5.2.11 on 2026-03-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtencionParto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='activo', max_length=20)),
            ],
        ),
    ]
