# Generated by Django 5.2.11 on 2026-03-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obstetricia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencionparto',
            name='paciente',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
