# Generated by Django 5.2.11 on 2026-09-23 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obstetricia', '0002_allow_blank_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencionparto',
            name='fecha_ingreso_dinamica',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atencionparto',
            name='numero_ingreso',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30),
        ),
        migrations.CreateModel(
            name='DocumentoRepositorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(db_index=True, max_length=50)),
                ('numero_ingreso', models.CharField(blank=True, default='', max_length=30)),
                ('formato', models.CharField(max_length=60)),
                ('referencia', models.CharField(blank=True, default='', max_length=64)),
                ('modo', models.CharField(max_length=10)),
                ('estado', models.CharField(db_index=True, max_length=10)),
                ('nombre_archivo', models.CharField(blank=True, default='', max_length=255)),
                ('ruta', models.CharField(blank=True, default='', max_length=500)),
                ('tamano_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('detalle_error', models.TextField(blank=True, default='')),
                ('enviado_por', models.CharField(blank=True, default='', max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('atencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_repositorio', to='obstetricia.atencionparto')),
            ],
            options={
                'verbose_name': 'Documento enviado al repositorio',
                'verbose_name_plural': 'Documentos enviados al repositorio',
                'ordering': ['-creado_en'],
            },
        ),
    ]
