# Generated by Django 5.2.11 on 2026-09-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obstetricia', '0003_numero_ingreso_y_documentos_repositorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoDocumentoRepositorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=255)),
                ('cedula', models.CharField(db_index=True, max_length=50)),
                ('numero_ingreso', models.CharField(max_length=30)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Consulta de documento del repositorio',
                'verbose_name_plural': 'Consultas de documentos del repositorio',
                'ordering': ['-creado_en'],
            },
        ),
    ]
